export const edition6 = {

	"edition": "6",
	"strategies":
		[
			"(Organic) machinery",
			"A very small object – Its centre",
			"Abandon desire",
			"Abandon normal instructions",
			"Abandon normal instruments",
			"Adding on",
			"All that happens is good",
			"Always give yourself credit for having more than personality",
			"Always the first steps",
			"Back up a few steps. What else could you have done?",
			"Be less critical more often",
			"Bridges – build – burn",
			"Call your mother and ask her what to do.",
			"Change ambiguities to specifics",
			"Change specifics to ambiguities",
			"Children singing",
			"Children speaking",
			"Children’s voices – speaking – singing",
			"Consider transitions",
			"Consult other sources: promising",
			"Consult other sources: unpromising",
			"Credibility of Intentions",
			"Define an area as 'safe' and use it as an anchor",
			"Describe the landscape in which this belongs.",
			"Destroy nothing",
			"Destroy the most important thing",
			"Disconnect from desire",
			"Discover your formulas and abandon them",
			"Display your talent",
			"Distorting time",
			"Do something sudden, destructive and unpredictable",
			"Do the last thing first",
			"Don’t avoid what is easy",
			"Faced with a choice, do both",
			"Feedback recordings into an acoustic situation",
			"First work alone, then work in unusual pairs.",
			"From nothing to more than nothing",
			"Give way to your worst impulse",
			"Go inside. Shut the door.",
			"Go outside. Shut the door.",
			"Go to an extreme, move back to a more comfortable place",
			"Go, make a demo about it",
			"Honour thy error as a hidden intention",
			"How would someone else do it?",
			"How would you explain this to your parents?",
			"Humanize something free of error",
			"Humility of Intentions",
			"Idiot glee",
			"Imagine a caterpillar moving",
			"Imagine the music as a moving chain or caterpillar",
			"Imagine the music as a series of disconnected events",
			"Instead of changing the thing, change the world around it.",
			"Intentions – credibility of – nobility of – humility of",
			"Into the impossible",
			"Is the style right?",
			"Is the tuning appropriate?",
			"Is the tuning intonation correct?",
			"Is there something missing?",
			"It is simply a matter or work",
			"Its centre",
			"Krawall!",
			"Left channel, right channel, centre channel",
			"List the qualities it has. List those you’d like.",
			"Listen in total darkness, or in a very large room, very quietly",
			"Look closely at the most embarrassing details and amplify.",
			"Lowest common denominator check – single beat – single note – single riff",
			"Magnify the most difficult details",
			"Make a blank valuable by putting it in an exquisite frame",
			"Make it more sensual",
			"Make what’s perfect more human",
			"Mechanize something idiosyncratic",
			"Move towards the unimportant",
			"Nobility of Intentions",
			"Once the search has begun, something will be found",
			"Only a part, not the whole",
			"Pae White’s non-blank graphic metacard",
			"Pay attention to distractions",
			"Picture of a man spotlighted",
			"Remove a restriction",
			"Remove the middle, extend the edges",
			"Retrace your steps",
			"Short circuit (example; a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
			"Shut the door and listen from outside",
			"Slow preparation, fast execution",
			"State the problem in words as clearly as possible",
			"Steal a solution.",
			"Take a walk and study the architecture",
			"Take away as much mystery as possible. What is left?",
			"Take away the important parts",
			"Tape your mouth",
			"Think – inside the work – outside the work",
			"Try faking it",
			"Use 'unqualified' people.",
			"Use an unacceptable color",
			"Use cliches",
			"Use something nearby as a model",
			"Use your own ideas",
			"Voice your suspicions",
			"What are the sections sections of?",
			"What are you really thinking about just now?",
			"What context would look right?",
			"What do you do? Now, what do you do best?",
			"What else is this like?",
			"What is the simplest solution?",
			"What most recently impressed you? How is it similar? What can you learn from it?",
			"What could you take from it?",
			"What to increase? What to reduce? What to maintain?",
			"What were the branch points in the evolution of this entity",
			"What were you really thinking about just now? Incorporate",
			"What would make this really successful?",
			"When is it for? Who is it for?",
			"Where is the edge?",
			"Which parts can be grouped?",
			"Who would make this really successful?",
			"Would anyone want it?",
			"Your mistake was a hidden intention"
		]
}